apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
  labels:
    app: container-linux-update-agent
  name: container-linux-update-agent
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: container-linux-update-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: container-linux-update-agent
    spec:
      serviceAccount: reboot-coordinator
      containers:
      - env:
        - name: UPDATE_AGENT_NODE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ko://github.com/pantheon-systems/cos-update-operator/cmd/update-agent
        imagePullPolicy: IfNotPresent
        name: update-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/dbus
          name: var-run-dbus
        - mountPath: /etc/coreos
          name: etc-coreos
        - mountPath: /usr/share/coreos
          name: usr-share-coreos
        - mountPath: /etc/os-release
          name: etc-os-release
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - key: node.pantheon.io/cos
        value: "true"
      volumes:
      - hostPath:
          path: /var/run/dbus
          type: ""
        name: var-run-dbus
      - hostPath:
          path: /mnt/disks/data/etc/coreos
          type: ""
        name: etc-coreos
      - hostPath:
          path: /mnt/disks/data/etc/coreos
          type: ""
        name: usr-share-coreos
      - hostPath:
          path: /etc/os-release
          type: ""
        name: etc-os-release
  templateGeneration: 6
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: reboot-coordinator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reboot-coordinator
subjects:
  - kind: ServiceAccount
    name: reboot-coordinator
    namespace: reboot-coordinator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: reboot-coordinator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - "extensions"
    resources:
      - daemonsets
    verbs:
      - get
