apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
  labels:
    app: cos-update-agent
  name: cos-update-agent
spec:
  selector:
    matchLabels:
      app: cos-update-agent
  template:
    metadata:
      labels:
        app: cos-update-agent
    spec:
      containers:
      - env:
        - name: UPDATE_AGENT_NODE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_SERVICE_HOST
          value: ""
        - name: KUBERNETES_SERVICE_PORT
          value: ""
        - name: KUBECONFIG
          value: "/var/lib/kubelet/kubeconfig"
        image: ko://github.com/pantheon-systems/cos-update-operator/cmd/update-agent
        imagePullPolicy: IfNotPresent
        name: update-agent
        volumeMounts:
        - mountPath: /etc/srv/kubernetes/pki
          name: etc-srv-kubernetes-pki
          readOnly: true
        - mountPath: /var/lib/kubelet
          name: var-lib-kubelet
          readOnly: true
        - mountPath: /var/run/dbus
          name: var-run-dbus
        - mountPath: /etc/coreos
          name: etc-coreos
        - mountPath: /usr/share/coreos
          name: usr-share-coreos
        - mountPath: /etc/os-release
          name: etc-os-release
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node.pantheon.io/cos
        value: "true"
      volumes:
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: var-lib-kubelet
      - hostPath:
          path: /etc/srv/kubernetes/pki
          type: Directory
        name: etc-srv-kubernetes-pki
      - hostPath:
          path: /var/run/dbus
          type: ""
        name: var-run-dbus
      - hostPath:
          path: /mnt/disks/data/etc/coreos
          type: ""
        name: etc-coreos
      - hostPath:
          path: /mnt/disks/data/etc/coreos
          type: ""
        name: usr-share-coreos
      - hostPath:
          path: /etc/os-release
          type: ""
        name: etc-os-release
  templateGeneration: 6
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
